## Training:
stat_ques_list: ["/home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json","/home/ndhuynh/data/simpsonsvqa/v1_Question_Val_simpsons_vqa.json", "/home/ndhuynh/data/simpsonsvqa/v1_Question_Test_Private_110496_simpsons_vqa.json"]
use_glove: True
train_question: '/home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json'
val_question: '/home/ndhuynh/data/simpsonsvqa/v1_Question_Val_simpsons_vqa.json'
test_question: '/home/ndhuynh/data/simpsonsvqa/v1_Question_Test_Private_110496_simpsons_vqa.json'
max_ques_len: 20
image_feature_output: 1024
word_embedding: 300
rnn_hidden_size: 512
img_size: 224
train_annotation: '/home/ndhuynh/data/simpsonsvqa/v1_Annotation_Train_simpsons_vqa.json'
val_annotation : '/home/ndhuynh/data/simpsonsvqa/v1_Annotation_Val_simpsons_vqa.json'
test_annotation : '/home/ndhuynh/data/simpsonsvqa/v1_Annotation_Test_Private_110496_simpsons_vqa.json'
stat_ann_list: ["/home/ndhuynh/data/simpsonsvqa/v1_Annotation_Train_simpsons_vqa.json","/home/ndhuynh/data/simpsonsvqa/v1_Annotation_Val_simpsons_vqa.json"]