stat_ques_list:
  - "v1_Question_Train_simpsons_vqa.json"
  - "v1_Question_Val_simpsons_vqa.json"
  - "v1_Question_Test_Private_110496_simpsons_vqa.json"
train_question: 'v1_Question_Train_simpsons_vqa.json'
val_question: 'v1_Question_Val_simpsons_vqa.json'
test_question: 'v1_Question_Test_Private_110496_simpsons_vqa.json'
stat_ann_list: 
  - "v1_Annotation_Train_simpsons_vqa.json"
  - "v1_Annotation_Val_simpsons_vqa.json"
train_annotation: 'v1_Annotation_Train_simpsons_vqa.json'
val_annotation : 'v1_Annotation_Val_simpsons_vqa.json'


train_image_path: "train_images"
val_image_path: "val_images"
test_image_path: "test_images"

question_dict: "./datasets/question_dicts_simpsons.pkl"
question_type: "./datasets/train_question_type_gpt_v6_simpsons.json"
