stat_ques_list:
  - "new_vqa2_train_question.json"
  - "new_vqa2_val_question.json"
  - "new_vqa2_test_question.json"
train_question: 'new_vqa2_train_question.json'
val_question: 'new_vqa2_val_question.json'
test_question: 'new_vqa2_test_question.json'
stat_ann_list: 
  - "new_vqa2_train_annotation.json"
  - "new_vqa2_val_annotation.json"
train_annotation: 'new_vqa2_train_annotation.json'
val_annotation : 'new_vqa2_val_annotation.json'


train_image_path: "train2014"
val_image_path: "val2014"
test_image_path: "train2014"

question_dict: "./datasets/question_dicts_vqav2.pkl"
question_type: "./datasets/train_question_type_gpt_v6_vqav2.json"
