stat_ques_list:
  - "v2_OpenEnded_mscoco_train2014_questions.json"
  - "v2_OpenEnded_mscoco_val2014_questions.json"
  - "v2_OpenEnded_mscoco_test-dev2015_questions.json"
train_question: 'v2_OpenEnded_mscoco_train2014_questions.json'
val_question: 'v2_OpenEnded_mscoco_val2014_questions.json'
test_question: 'v2_OpenEnded_mscoco_test-dev2015_questions.json'
stat_ann_list: 
  - "v2_mscoco_train2014_annotations.json"
  - "v2_mscoco_val2014_annotations.json"
train_annotation: 'v2_mscoco_train2014_annotations.json'
val_annotation : 'v2_mscoco_val2014_annotations.json'


train_image_path: "train2014"
val_image_path: "val2014"
test_image_path: "test2015"

question_dict: "./datasets/question_dicts_vqav2.pkl"
question_type: "./datasets/train_question_type_gpt_v6_vqav2.json"
